
let defaultList =  [
    {
        name: 'list1',
        id: 1,
        checked: true,
        task: [
            {
                title: 'task 1',
                id: 1,
                repeat: true,
                time: 123,
                date: 1,
                listName: 'list1',
                description: 'Lorem ipsum dolor sit amet.',
                Complete: false,
            },
            {
                title: 'task 2',
                id: 2,
                repeat: false,
                time: 789,
                date: 2,
                listName: 'list1',
                description: 'Consectetur adipiscing elit.',
                Complete: true,
            },
            {
                title: 'task 3',
                id: 3,
                repeat: false,
                time: 789,
                date: 3,
                listName: 'list1',
                description: 'Consectetur adipiscing elit.',
                Complete: true,
            },
            {
                title: 'task 4',
                id: 4,
                repeat: false,
                time: 789,
                date: 4,
                listName: 'list1',
                description: 'Consectetur adipiscing elit.',
                Complete: true,
            },
            // {
            //     title: 'task 5',
            //     id: 5,
            //     repeat: false,
            //     time: 789,
            //     date: 5,
            //     listName: 'list1',
            //     description: 'Consectetur adipiscing elit.',
            //     Complete: true,
            // },
            // {
            //     title: 'task 6',
            //     id: 6,
            //     repeat: false,
            //     time: 789,
            //     date: 6,
            //     listName: 'list1',
            //     description: 'Consectetur adipiscing elit.',
            //     Complete: true,
            // },
            // {
            //     title: 'task 7',
            //     id: 7,
            //     repeat: false,
            //     time: 789,
            //     date: 7,
            //     listName: 'list1',
            //     description: 'Consectetur adipiscing elit.',
            //     Complete: true,
            // },
            // {
            //     title: 'task 8',
            //     id: 8,
            //     repeat: false,
            //     time: 789,
            //     date: 8,
            //     listName: 'list1',
            //     description: 'Consectetur adipiscing elit.',
            //     Complete: true,
            // },
            // {
            //     title: 'task 9',
            //     id: 9,
            //     repeat: false,
            //     time: 789,
            //     date: 9,
            //     listName: 'list1',
            //     description: 'Consectetur adipiscing elit.',
            //     Complete: true,
            // },
            
        ],
    },
    // {
    //     name: 'list2',
    //     id: 2,
    //     checked: true,
    //     task: [
    //         {
    //             title: 'task3',
    //             id: 3,
    //             repeat: true,
    //             time: 234,
    //             date: 567,
    //             listName: 'list2',
    //             description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    //             Complete: false,
    //         },
    //     ],
    // },
    // {
    //     name: 'list3',
    //     id: 3,
    //     checked: true,
    //     task: [],
    // },
    // {
    //     name: 'list4',
    //     id: 4,
    //     checked: false,
    //     task: [],
    // },
];

export default defaultList;